# This helm chart simply pulls in the metallb helm chart
apiVersion: v2
name: traefik
version: 0.1.0
dependencies:
  - name: traefik
    version: "10.14.2"
    repository: https://helm.traefik.io/traefik
